import { describe, expect, it } from "bun:test";
import {
  readBuiltinToolSources,
  readVariablesSource,
  renderManifest,
} from "./gen-langgraph-tools";

describe("gen-langgraph-tools", () => {
  describe("renderManifest", () => {
    it("renders the generated TS module correctly", () => {
      const sources = {
        tool_a: "def tool_a():\\n    pass\\n",
        tool_b: 'def tool_b():\\n    print("hello")\\n',
      };
      const variablesSource = "def get_vars():\\n    return {}\\n";

      const manifest = renderManifest(sources, variablesSource);

      // Verify header comments
      expect(manifest).toContain("// GENERATED by scripts/gen-langgraph-tools.ts — do not edit by hand.");

      // Verify BUILTIN_TOOL_SOURCES object creation
      expect(manifest).toContain("export const BUILTIN_TOOL_SOURCES: Record<string, string> = {");
      expect(manifest).toContain('"tool_a": "def tool_a():\\\\n    pass\\\\n",');
      expect(manifest).toContain('"tool_b": "def tool_b():\\\\n    print(\\"hello\\")\\\\n",');

      // Verify VARIABLES_PY_SOURCE export
      expect(manifest).toContain('export const VARIABLES_PY_SOURCE = "def get_vars():\\\\n    return {}\\\\n";');
    });

    it("handles empty sources map", () => {
      const sources = {};
      const variablesSource = "";

      const manifest = renderManifest(sources, variablesSource);

      expect(manifest).toContain("export const BUILTIN_TOOL_SOURCES: Record<string, string> = {\n\n};");
      expect(manifest).toContain('export const VARIABLES_PY_SOURCE = "";');
    });
  });

  describe("readBuiltinToolSources", () => {
    it("reads builtin tools from disk and returns a record", async () => {
      const sources = await readBuiltinToolSources();

      expect(typeof sources).toBe("object");
      expect(sources).not.toBeNull();

      // We expect at least a few common tools to be there based on built-in-sources.generated.ts
      expect(sources).toHaveProperty("read");
      expect(typeof sources.read).toBe("string");
      expect(sources.read.length).toBeGreaterThan(0);

      expect(sources).toHaveProperty("skill");
      expect(typeof sources.skill).toBe("string");

      expect(sources).toHaveProperty("sleep");
      expect(typeof sources.sleep).toBe("string");

      // Verify the returned keys are sorted alphabetically
      const keys = Object.keys(sources);
      const sortedKeys = [...keys].sort();
      expect(keys).toEqual(sortedKeys);
    });
  });

  describe("readVariablesSource", () => {
    it("reads variables.py from disk and returns its content", async () => {
      const variablesSource = await readVariablesSource();

      expect(typeof variablesSource).toBe("string");
      expect(variablesSource.length).toBeGreaterThan(0);

      // Should contain some expected python code from variables.py
      // such as imports or definitions
      expect(variablesSource).toContain("import");
    });
  });
});
