import { describe, expect, it } from "bun:test";
import {
  readBuiltinToolSources,
  readVariablesSource,
  renderManifest,
} from "./gen-langgraph-tools";

describe("gen-langgraph-tools", () => {
  describe("renderManifest", () => {
    it("renders a valid TypeScript module with sources and variables", () => {
      const sources = {
        tool1: "print('tool1')",
        tool2: "print('tool2')",
      };
      const variablesSource = "def current_date():\n    return '2023-01-01'";

      const output = renderManifest(sources, variablesSource);

      expect(output).toContain("// GENERATED by scripts/gen-langgraph-tools.ts — do not edit by hand.");
      expect(output).toContain("export const BUILTIN_TOOL_SOURCES: Record<string, string> = {");
      expect(output).toContain('"tool1": "print(\'tool1\')",');
      expect(output).toContain('"tool2": "print(\'tool2\')",');
      expect(output).toContain('export const VARIABLES_PY_SOURCE = "def current_date():\\n    return \'2023-01-01\'";');
    });

    it("handles empty sources correctly", () => {
      const sources = {};
      const variablesSource = "def current_date():\n    return '2023-01-01'";

      const output = renderManifest(sources, variablesSource);

      expect(output).toContain("export const BUILTIN_TOOL_SOURCES: Record<string, string> = {\n\n};");
      expect(output).toContain('export const VARIABLES_PY_SOURCE = "def current_date():\\n    return \'2023-01-01\'";');
    });
  });

  describe("readBuiltinToolSources", () => {
    it("reads the builtin tool sources from the file system", async () => {
      const sources = await readBuiltinToolSources();
      expect(Object.keys(sources).length).toBeGreaterThan(0);

      // Check that a known tool like 'read' is present
      expect(sources).toHaveProperty("read");
      expect(typeof sources.read).toBe("string");
      expect(sources.read).toContain("def read(");
    });
  });

  describe("readVariablesSource", () => {
    it("reads the variables.py source from the file system", async () => {
      const source = await readVariablesSource();
      expect(typeof source).toBe("string");
      expect(source).toContain("def current_date(");
      expect(source).toContain("def available_skills(");
    });
  });
});
